#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: goods-route # 当前路由的标识, 要求唯一
#          uri: lb://goods-service
#          order: 1
#          predicates:
#            - Path=/api/goods/** # 当请求路径满足Path指定的规则时,才进行路由转发
#          filters:
#            - StripPrefix=1 # 转发之前去掉0层路径
#
#        - id: shop_route # 当前路由的标识, 要求唯一
#          uri: lb://shop-service
#          order: 1
#          predicates:
#            - Path=/shop/** # 当请求路径满足Path指定的规则时,才进行路由转发
#          filters:
#            - StripPrefix=0 # 转发之前去掉1层路径
#spring:
#  cloud:
#    sentinel:
#      #配置限流之后的响应内容
#      scg:
#        fallback:
#          # 两种模式：一种是response返回文字提示信息，一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
#          mode: response
#          # 响应的状态
#          response-status: 426
#          # 响应体
#          response-body: '{"code": 426,"message": "限流了，稍后重试！"}'